# config/database.ym
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_user
  password: 05092004
  host: db
  port: 3306
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: g_prod_development

test:
  <<: *default
  database: g_prod_test

production:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
